# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  stageBuildConfiguration: '$(StageBuildConfig)'
  productionBuildConfiguration: '$(ProductionBuildConfig)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

# Display Nuevo Foundation and Current Year
- script: |
    echo "Nuevo Foundation $(date +'%Y')"
    echo "                                            @@@%%%%%%%%@@@                                          "
    echo "                                          @%*:..........:*@@                                        "
    echo "                                        @%-..            ..-%@                                      "
    echo "                                       @%++++++++++++++:.   .*@                                     "
    echo "                        @@@@@@@@@@@@@@@#===============-:::::-%@@@@@@@@@@@@                         "
    echo "                       %#-------------------------------------------------#@                       "
    echo "                       %+                                                .*@                        "
    echo "                       %+                                                .*@                        "
    echo "                       %+ .:------------------------------------------:. .*@                        "
    echo "                      @%+ :%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%- .*@@                       "
    echo "                    @%**+ :%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%- .*-=#%                     "
    echo "                   @%:.++ :%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%- .*=#:=%                    "
    echo "                   @-.=++ :%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%- .*=#:.-@                   "
    echo "                  @%.:#++ :%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%- .*=#:..%@                  "
    echo "                   @.:#++ :%@@@@@%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@%#@@@@@%- .*=#:..%                   "
    echo "                   @*:#++ :%@@@@#==+@@@@@@@@@@@@@@@@@@@@@@@@@@%==+@@@@%- .*=#:.#@                   "
    echo "                    @##++ :%@@@@*===%@@@@@@@@@@@@@@@@@@@@@@@@@*==+%@@@%- .*=#+#@                    "
    echo "                     @%#+ :%@@@@#===%@@@@@@@@@@@@@@@@@@@@@@@@@#==+@@@@%- .*#%@@                     "
    echo "                       %+ :%@@@@@#*%@@@@@@@@@@@@@@@@@@@@@@@@@@@#*%@@@@%- .*@                         "
    echo "                       %+ :%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%- .*@                         "
    echo "                       %+ .+##########################################+: .*@                         "
    echo "                       %+.................................................*@                         "
    echo "                       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                         "
  displayName: 'Nuevo Foundation $(date +'%Y')'

#- script : | 
#    ./node_modules/.bin/eslint src/**/*.{ts,tsx}
#  displayName: 'run eslint'

- script: |
    npm run test-ci
  displayName: 'npm run test-ci'

- script: |
    npm run "$(stageBuildConfiguration)"
  displayName: 'npm run optimized $(stageBuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: '**/build/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true 
    overWrite: true 
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  

- task: PublishBuildArtifacts@1
  displayName: 'Publish src to: $(Build.ArtifactStagingDirectory)'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'stage' 
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  

- script: |
    npm run "$(productionBuildConfiguration)"
  displayName: 'npm run optimized $(productionBuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: '**/build/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true 
    overWrite: true
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  

- task: PublishBuildArtifacts@1
  displayName: 'Publish src to: $(Build.ArtifactStagingDirectory)'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'production' 
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
