# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  stageBuildConfiguration: '$(StageBuildConfig)'
  productionBuildConfiguration: '$(ProductionBuildConfig)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

#- script : | 
#    ./node_modules/.bin/eslint src/**/*.{ts,tsx}
#  displayName: 'run eslint'

- script: |
    npm run test-ci
  displayName: 'npm run test-ci'

- script: |
    npm run "$(stageBuildConfiguration)"
  displayName: 'npm run optimized $(stageBuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: '**/build/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  

- task: PublishBuildArtifacts@1
  displayName: 'Publish src to: $(Build.ArtifactStagingDirectory)'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'stage' 
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  

- script: |
    npm run "$(productionBuildConfiguration)"
  displayName: 'npm run optimized $(productionBuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: '**/build/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  

- task: PublishBuildArtifacts@1
  displayName: 'Publish src to: $(Build.ArtifactStagingDirectory)'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'production' 
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  